let cfg={},docs={},activeDoc='soul',running=false,currentMemory=null,memoryRows=[],characterData={images:[],primary:null,profile:''};
const $=id=>document.getElementById(id), val=id=>$(id).value, num=id=>Number(val(id)), checked=id=>$(id).checked;
function parseRoom(value){const s=String(value||'').trim();if(/^\d+$/.test(s))return Number(s);const m=s.match(/live\.bilibili\.com\/(?:blanc\/)?(\d+)/i);return m?Number(m[1]):0}
function roomUrl(id){return id?`https://live.bilibili.com/${id}`:''}
function updateRoomState(source){const id=parseRoom(source.value);for(const sid of ['roomIdState','liveRoomIdState']){const el=$(sid);el.textContent=id?`已识别 · ${id}`:(source.value?'无法识别':'等待输入');el.className=id?'valid':(source.value?'invalid':'')}return id}
function updateTriggerHelp(){const mode=$('liveTriggerMode').value;const help={all:'所有新弹幕都会触发语音回复；同一用户仍受冷却时间限制。',mention:'只有包含助手名称的弹幕才会触发，适合弹幕较多的直播间。',prefix:'只有以指定前缀开头的弹幕才会触发，最容易控制。'}[mode];$('triggerModeHelp').textContent=help;$('liveTriggerModeHelp').textContent=help}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`请求失败 ${r.status}`);return d}
function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.className=error?'show error':'show';setTimeout(()=>t.className='',2600)}
function arr(s){return s.split(/[,，]/).map(x=>x.trim()).filter(Boolean)}
function provider(){return cfg.llm.providers[$('provider').value]}
function fill(){
 cfg.memory_write=cfg.memory_write||{mode:'important',importance_threshold:70,analyze_with_llm:true,min_message_length:4,max_daily_writes:20,always_keywords:[],ignore_keywords:[]};
 cfg.image_generation=cfg.image_generation||{mode:'images',base_url:'https://api.example.com/v1',model:'your-image-model',size:'1024x1024',api_key_env:'IMAGE_API_KEY',timeout_seconds:180};
 $('roomId').value=$('liveRoomId').value=roomUrl(cfg.app.room_id);updateRoomState($('roomId'));$('dryRun').checked=cfg.app.dry_run!==false;$('sendDanmaku').checked=!!cfg.app.send_danmaku;
 $('welcomeEnabled').checked=cfg.bilibili.welcome_enabled!==false;$('welcomeTemplate').value=cfg.bilibili.welcome_template||'';$('welcomeCooldown').value=cfg.bilibili.welcome_cooldown_seconds||1800;
 $('replyEnabled').checked=cfg.reply.enabled!==false;$('triggerMode').value=$('liveTriggerMode').value=cfg.reply.trigger_mode||'mention';updateTriggerHelp();$('botNames').value=(cfg.reply.bot_names||[]).join('，');$('prefixes').value=(cfg.reply.prefixes||[]).join('，');$('cooldown').value=$('replyCooldown').value=cfg.reply.cooldown_seconds||12;
 $('provider').value=cfg.llm.provider||'deepseek';fillProvider();$('temperature').value=cfg.llm.temperature;$('maxTokens').value=cfg.llm.max_tokens;
 $('ttsEnabled').checked=cfg.tts.enabled!==false;$('ttsAutoStart').checked=!!cfg.tts.auto_start;$('ttsCommand').value=cfg.tts.start_command||'';$('ttsUrl').value=cfg.tts.url||'';$('ttsHealth').value=cfg.tts.health_url||'';$('ttsModel').value=cfg.tts.model||'';$('ttsReference').value=cfg.tts.reference||'';$('ttsTimeout').value=cfg.tts.startup_timeout_seconds||240;
 const mw=cfg.memory_write;$('memoryWriteMode').value=mw.mode||'important';$('memoryThreshold').value=mw.importance_threshold??70;$('memoryThresholdValue').textContent=$('memoryThreshold').value;$('memoryDailyLimit').value=mw.max_daily_writes??20;$('memoryMinLength').value=mw.min_message_length??4;$('memoryAlwaysKeywords').value=(mw.always_keywords||[]).join('，');$('memoryIgnoreKeywords').value=(mw.ignore_keywords||[]).join('，');$('memoryAnalyzeLlm').checked=mw.analyze_with_llm!==false;updateMemoryMode();
 const ig=cfg.image_generation;$('imageApiMode').value=ig.mode||'images';$('imageApiBase').value=ig.base_url||'';$('imageApiModel').value=ig.model||'';$('imageApiSize').value=ig.size||'1024x1024';
 $('sendStatus').textContent=cfg.app.send_danmaku?'已启用':'已关闭';showDoc();
}
function fillProvider(){const p=provider();$('modelName').value=p.model||'';$('baseUrl').value=p.base_url||''}
function collect(){
 cfg.app.room_id=parseRoom(val('liveRoomId'))||parseRoom(val('roomId'));if(!cfg.app.room_id)throw new Error('请粘贴有效的B站直播间地址或输入房间号');cfg.app.dry_run=checked('dryRun');cfg.app.send_danmaku=checked('sendDanmaku');
 cfg.bilibili.welcome_enabled=checked('welcomeEnabled');cfg.bilibili.welcome_template=val('welcomeTemplate');cfg.bilibili.welcome_cooldown_seconds=num('welcomeCooldown');
 cfg.reply.enabled=checked('replyEnabled');cfg.reply.trigger_mode=val('liveTriggerMode');cfg.reply.bot_names=arr(val('botNames'));cfg.reply.prefixes=arr(val('prefixes'));cfg.reply.cooldown_seconds=num('replyCooldown');
 cfg.llm.provider=val('provider');const p=provider();p.model=val('modelName');p.base_url=val('baseUrl');cfg.llm.temperature=num('temperature');cfg.llm.max_tokens=num('maxTokens');
 Object.assign(cfg.tts,{enabled:checked('ttsEnabled'),auto_start:checked('ttsAutoStart'),start_command:val('ttsCommand'),url:val('ttsUrl'),health_url:val('ttsHealth'),model:val('ttsModel'),reference:val('ttsReference'),startup_timeout_seconds:num('ttsTimeout')});docs[activeDoc]=$('docEditor').value;
 Object.assign(cfg.memory_write,{mode:val('memoryWriteMode'),importance_threshold:num('memoryThreshold'),max_daily_writes:num('memoryDailyLimit'),min_message_length:num('memoryMinLength'),always_keywords:arr(val('memoryAlwaysKeywords')),ignore_keywords:arr(val('memoryIgnoreKeywords')),analyze_with_llm:checked('memoryAnalyzeLlm')});
 Object.assign(cfg.image_generation,{mode:val('imageApiMode'),base_url:val('imageApiBase').replace(/\/$/,''),model:val('imageApiModel'),size:val('imageApiSize'),api_key_env:'IMAGE_API_KEY'});
}
async function save(){collect();await Promise.all([api('/api/config',{method:'PUT',body:JSON.stringify(cfg)}),api('/api/docs',{method:'PUT',body:JSON.stringify(docs)}),api('/api/secrets',{method:'PUT',body:JSON.stringify({DEEPSEEK_API_KEY:val('deepseekKey'),MIMO_API_KEY:val('mimoKey'),CUSTOM_API_KEY:val('customKey'),IMAGE_API_KEY:val('imageKey'),BILIBILI_COOKIE:val('biliCookie')})})]);['deepseekKey','mimoKey','customKey','imageKey','biliCookie'].forEach(x=>$(x).value='');toast('配置已安全保存');loadSecrets()}
const docMeta={soul:['SOUL.md','角色的核心性格','描述助手是谁、如何说话，以及希望带给直播间的感觉。'],rules:['RULES.md','公开回复的边界','设置安全要求、禁止事项和直播间表达规则。'],abilities:['ABILITIES.md','助手具备的能力','告诉模型可以做什么，以及哪些能力不应假装具备。']};
function showDoc(){const m=docMeta[activeDoc];$('docBadge').textContent=m[0];$('docTitle').textContent=m[1];$('docHelp').textContent=m[2];$('docEditor').value=docs[activeDoc]||''}
async function loadSecrets(){const s=await api('/api/secrets');[['deepseekState','DEEPSEEK_API_KEY'],['mimoState','MIMO_API_KEY'],['customState','CUSTOM_API_KEY'],['imageKeyState','IMAGE_API_KEY']].forEach(([id,k])=>$(id).textContent=s[k]?'✓ 已保存':'未设置')}
async function refreshStatus(){try{const s=await api('/api/status');running=s.assistant;$('assistantStatus').textContent=running?'运行中':'未运行';$('svcStatus').textContent=s.svc?'已就绪':'未启动';$('runBtn').textContent=running?'停止直播助手':'启动直播助手';$('sideStatus').textContent=running?'直播助手运行中':(s.svc?'语音服务已就绪':'服务待启动');$('sideDot').classList.toggle('on',running||s.svc)}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadMessages(){try{const d=await api('/api/messages?limit=150');$('messageList').innerHTML=d.messages.length?d.messages.map(m=>{const state=m.status==='success'?['已回复','ok']:(m.status==='error'?['失败','bad']:(m.status==='triggered'?['已触发','wait']:['已跳过','skip']));const detail=m.reply?`<small>AI：${esc(m.reply)}</small>`:(m.reason?`<small>${esc(m.reason)}</small>`:(m.error?`<small>${esc(m.error)}</small>`:''));return `<div class="message-row"><span class="message-time">${esc((m.time||'').replace('T',' '))}</span><span class="message-user">${esc(m.user)}</span><div class="message-text">${esc(m.message)}${detail}</div><span class="message-status ${state[1]}">${state[0]}</span></div>`}).join(''):'<div class="empty">等待直播间消息…</div>'}catch(e){$('messageList').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function memoryContent(m){return m.content||([m.message,m.reply&&`AI回复：${m.reply}`].filter(Boolean).join(' · '))||'（空记忆）'}
function updateMemoryMode(){const mode=val('memoryWriteMode');const labels={important:'仅重要事件',off:'自动写入已关闭',all:'所有回复'};$('memoryModeBadge').textContent=labels[mode];const disabled=mode!=='important';['memoryThreshold','memoryMinLength','memoryAlwaysKeywords','memoryIgnoreKeywords','memoryAnalyzeLlm'].forEach(id=>$(id).disabled=disabled);$('memoryDailyLimit').disabled=mode==='off'}
async function loadMemories(){try{const q=encodeURIComponent(val('memorySearch').trim());const d=await api(`/api/memories?limit=500&q=${q}`);memoryRows=d.memories;$('memoryCount').textContent=`${d.total} 条记忆`;$('memoryList').innerHTML=memoryRows.length?memoryRows.map((m,i)=>`<article class="memory-item" data-memory-index="${i}" tabindex="0"><div class="memory-meta"><span class="memory-type">${esc(m.type||'memory')}</span><span class="memory-date">${esc((m.time||'').replace('T',' '))}</span></div><h4>${esc(m.user||'全局记忆')}</h4><p>${esc(memoryContent(m))}</p><div class="memory-tags">${(Array.isArray(m.tags)?m.tags:[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div></article>`).join(''):'<div class="memory-empty">没有找到记忆，点击右上角添加第一条。</div>';document.querySelectorAll('[data-memory-index]').forEach(el=>{el.onclick=()=>openMemory(memoryRows[Number(el.dataset.memoryIndex)]);el.onkeydown=e=>{if(e.key==='Enter')openMemory(memoryRows[Number(el.dataset.memoryIndex)])}})}catch(e){$('memoryList').innerHTML=`<div class="memory-empty">${esc(e.message)}</div>`}}
function openMemory(m=null){currentMemory=m;$('memoryDialogMode').textContent=m?'编辑记录':'新增记录';$('memoryDialogTitle').textContent=m?'修改长期记忆':'添加一条长期记忆';$('memoryType').value=m?.type||'manual';$('memoryUser').value=m?.user||'';$('memoryContent').value=m?memoryContent(m):'';$('memoryTags').value=Array.isArray(m?.tags)?m.tags.join('，'):'';$('memoryRaw').value=m?JSON.stringify(Object.fromEntries(Object.entries(m).filter(([k])=>!k.startsWith('_'))),null,2):'';$('rawMemoryWrap').open=false;$('deleteMemory').style.visibility=m?'visible':'hidden';$('memoryModal').classList.add('open');$('memoryModal').setAttribute('aria-hidden','false')}
function closeMemory(){currentMemory=null;$('memoryModal').classList.remove('open');$('memoryModal').setAttribute('aria-hidden','true')}
async function saveMemory(){let payload={};if(currentMemory&&val('memoryRaw').trim()){try{payload=JSON.parse(val('memoryRaw'))}catch{throw new Error('原始记忆字段不是有效 JSON')}}Object.assign(payload,{type:val('memoryType'),user:val('memoryUser').trim(),content:val('memoryContent').trim(),tags:arr(val('memoryTags'))});if(!payload.content)throw new Error('记忆内容不能为空');const url=currentMemory?`/api/memories/${encodeURIComponent(currentMemory._id)}`:'/api/memories';await api(url,{method:currentMemory?'PUT':'POST',body:JSON.stringify(payload)});closeMemory();await loadMemories();toast('记忆已保存，下一次回复即可使用')}
async function removeMemory(){if(!currentMemory||!confirm('确定删除这条记忆吗？删除后无法恢复。'))return;await api(`/api/memories/${encodeURIComponent(currentMemory._id)}`,{method:'DELETE'});closeMemory();await loadMemories();toast('记忆已删除')}
async function loadCharacter(){try{characterData=await api('/api/character');$('characterProfile').value=characterData.profile||'';$('characterCount').textContent=`${characterData.images.length} 张图片`;renderCharacter()}catch(e){$('characterGrid').innerHTML=`<div class="character-empty">${esc(e.message)}</div>`}}
function renderCharacter(){$('characterGrid').innerHTML=characterData.images.length?characterData.images.map(item=>`<article class="character-card"><div class="character-image">${characterData.primary===item.id?'<span class="primary-ribbon">主形象</span>':''}<img src="/api/character/image/${encodeURIComponent(item.filename)}" alt="${esc(item.label)}"></div><div class="character-info"><h4>${esc(item.label)}</h4><p>${esc((item.tags||[]).join(' · ')||item.original_name)}</p><div class="character-actions"><button data-primary-image="${esc(item.id)}" class="${characterData.primary===item.id?'primary-image':''}">${characterData.primary===item.id?'当前主形象':'设为主形象'}</button><button data-remove-image="${esc(item.id)}" class="remove-image">删除</button></div></div></article>`).join(''):'<div class="character-empty">还没有上传角色形象。</div>';document.querySelectorAll('[data-primary-image]').forEach(b=>b.onclick=()=>setPrimaryImage(b.dataset.primaryImage));document.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>removeCharacterImage(b.dataset.removeImage))}
async function uploadCharacter(){const file=$('characterFile').files[0];if(!file)throw new Error('请先选择图片');const form=new FormData();form.append('file',file);form.append('label',val('characterLabel'));form.append('tags',val('characterTags'));const r=await fetch('/api/character/images',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'上传失败');$('characterFile').value='';$('characterLabel').value='';$('characterTags').value='';await loadCharacter();toast('角色形象已上传')}
async function setPrimaryImage(id){await api('/api/character',{method:'PUT',body:JSON.stringify({primary:id})});await loadCharacter();toast('主形象已更新')}
async function removeCharacterImage(id){if(!confirm('确定删除这张角色形象吗？'))return;await api(`/api/character/images/${encodeURIComponent(id)}`,{method:'DELETE'});await loadCharacter();toast('形象图片已删除')}
async function saveCharacterProfile(){await api('/api/character',{method:'PUT',body:JSON.stringify({profile:val('characterProfile')})});toast('角色外观说明已保存')}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={overview:'直播总览',live:'直播与回复',model:'智能模型',voice:'语音服务',messages:'消息日志',memory:'记忆管理',character:'角色形象',persona:'人格工作区',security:'密钥与登录'};$('pageTitle').textContent=titles[page];if(page==='messages')loadMessages();if(page==='memory')loadMemories();if(page==='character')loadCharacter()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{docs[activeDoc]=$('docEditor').value;activeDoc=b.dataset.doc;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));showDoc()});
$('provider').onchange=fillProvider;$('roomId').oninput=()=>{$('liveRoomId').value=$('roomId').value;updateRoomState($('roomId'))};$('liveRoomId').oninput=()=>{$('roomId').value=$('liveRoomId').value;updateRoomState($('liveRoomId'))};$('triggerMode').onchange=()=>{$('liveTriggerMode').value=$('triggerMode').value;updateTriggerHelp()};$('liveTriggerMode').onchange=()=>{$('triggerMode').value=$('liveTriggerMode').value;updateTriggerHelp()};$('cooldown').oninput=()=>$('replyCooldown').value=$('cooldown').value;$('replyCooldown').oninput=()=>$('cooldown').value=$('replyCooldown').value;
$('saveBtn').onclick=()=>save().catch(e=>toast(e.message,true));$('runBtn').onclick=async()=>{try{if(!running){await save();await api('/api/assistant/start',{method:'POST'})}else await api('/api/assistant/stop',{method:'POST'});await refreshStatus();toast(running?'直播助手已启动':'直播助手已停止')}catch(e){toast(e.message,true)}};
$('testTts').onclick=$('quickVoice').onclick=async()=>{try{await save();toast('正在生成语音，请稍候');await api('/api/test/tts',{method:'POST',body:JSON.stringify({text:$('ttsTestText').value})});toast('语音生成并播放完成')}catch(e){toast(e.message,true)}};
$('testLlm').onclick=async()=>{try{await save();$('llmResult').textContent='正在等待模型回复…';const d=await api('/api/test/llm',{method:'POST',body:JSON.stringify({text:$('llmTestText').value})});$('llmResult').textContent=d.answer;toast('AI 接口测试成功')}catch(e){$('llmResult').textContent=e.message;toast(e.message,true)}};
$('refreshMessages').onclick=loadMessages;
$('addMemory').onclick=()=>openMemory();$('closeMemory').onclick=$('cancelMemory').onclick=closeMemory;$('saveMemory').onclick=()=>saveMemory().catch(e=>toast(e.message,true));$('deleteMemory').onclick=()=>removeMemory().catch(e=>toast(e.message,true));$('searchMemory').onclick=loadMemories;$('memorySearch').onkeydown=e=>{if(e.key==='Enter')loadMemories()};$('memoryModal').onclick=e=>{if(e.target===$('memoryModal'))closeMemory()};
$('memoryWriteMode').onchange=updateMemoryMode;$('memoryThreshold').oninput=()=>$('memoryThresholdValue').textContent=$('memoryThreshold').value;
$('uploadCharacter').onclick=()=>uploadCharacter().catch(e=>toast(e.message,true));$('saveCharacterProfile').onclick=()=>saveCharacterProfile().catch(e=>toast(e.message,true));$('characterFile').onchange=()=>{const f=$('characterFile').files[0];if(f&&!val('characterLabel'))$('characterLabel').value=f.name.replace(/\.[^.]+$/,'')};
(async()=>{try{[cfg,docs]=await Promise.all([api('/api/config'),api('/api/docs')]);fill();await loadSecrets();await refreshStatus();setInterval(refreshStatus,5000);setInterval(()=>{if($('messages').classList.contains('active'))loadMessages()},3000)}catch(e){toast(e.message,true)}})();
